package gov.ca.cwds.data.persistence.cms;

import gov.ca.cwds.data.persistence.PersistentObject;
import java.io.Serializable;
import java.time.LocalDateTime;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;
import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

/**
 * @author CWDS CALS API Team
 *
 * The converted (phonetic) Names of the SUBSTITUTE CARE PROVIDER generated by the SSA-Name3
 * algorithm to be used for Substitute Care Provider Search.    For each name, there could be up to
 * 25 Phonetic Keys produced by the SSA-Name3 algorithm.
 */
@Entity
@Table(name = "SCP_PHTT")
@IdClass(SubCareProviderPhoneticNamePK.class)
@SuppressWarnings({"squid:S3437"}) //LocalDate is serializable
public class SubCareProviderPhoneticName implements PersistentObject {

  /**
   * PHONETIC_NAME - The five characters phonetic search key generated by the SSA-Name3 algorithm to
   * be used for substitute Care Provider Search.
   */
  @Id
  @Column(name = "PHONETC_NM", nullable = false, length = 8)
  private String phonetcNm;

  /**
   * FKSB_PVDRT - Mandatory Foreign key that DEFINES_THE_SEARCH_KEY_FOR a SUBSTITUTE_CARE_PROVIDER.
   */
  @Id
  @Column(name = "FKSB_PVDRT", nullable = false, length = 10)
  private String fksbPvdrt;

  /**
   * LAST_UPDATE_ID - The ID (a sequential 3 digit base 62 number generated by the system) of the
   * STAFF PERSON or batch program which made the last update to an occurrence of this entity type.
   */
  @Basic
  @Column(name = "LST_UPD_ID", nullable = false, length = 3)
  private String lstUpdId;

  /**
   * LAST_UPDATE_TIMESTAMP - The time and date of the most recent update to an occurrence of this
   * entity type.
   */
  @Basic
  @Column(name = "LST_UPD_TS", nullable = false)
  private LocalDateTime lstUpdTs;

  public String getPhonetcNm() {
    return phonetcNm;
  }

  public void setPhonetcNm(String phonetcNm) {
    this.phonetcNm = phonetcNm;
  }

  public String getFksbPvdrt() {
    return fksbPvdrt;
  }

  public void setFksbPvdrt(String fksbPvdrt) {
    this.fksbPvdrt = fksbPvdrt;
  }

  public String getLstUpdId() {
    return lstUpdId;
  }

  public void setLstUpdId(String lstUpdId) {
    this.lstUpdId = lstUpdId;
  }

  public LocalDateTime getLstUpdTs() {
    return lstUpdTs;
  }

  public void setLstUpdTs(LocalDateTime lstUpdTs) {
    this.lstUpdTs = lstUpdTs;
  }

  @Override
  public boolean equals(Object o) {
    return EqualsBuilder.reflectionEquals(this, o);
  }

  @Override
  public int hashCode() {
    return HashCodeBuilder.reflectionHashCode(this);
  }

  @Override
  public Serializable getPrimaryKey() {
    return new SubCareProviderPhoneticNamePK(phonetcNm, fksbPvdrt);
  }
}
