/*
      *Code:* R - 11037

      *Rule Txt*
      In the Resource Management Application,
       a staff person with the privilege of "Resource Mgmt Placement Facility Maint" can add
       a Resource Family Home

      *Logic*
      Allow Resource Family Home add if (STAFF_PERSON (logged on user) > USER_ID > STAFF_PERSON_PRIVILEGE.Level_Of_Auth_Privilege_Code = 'P' and STAFF_PERSON_PRIVILEGE.Level_Of_Auth_Privilege_Type = 'Resource Mgmt Placement Facility Maint')
      */

import gov.ca.cwds.security.realm.PerryAccount;
import gov.ca.cwds.data.legacy.cms.entity.SubstituteCareProvider;

global Boolean authorizationResult;

rule "R-11037"
  dialect "mvel"
  agenda-group "substitute-care-provider-authorization-agenda"
when
    $placementHome: PlacementHome()
    PerryAccount(privileges contains "Resource Mgmt Placement Facility Maint")
then
    kcontext.getKieRuntime().setGlobal("authorizationResult", true);
    retract($placementHome);
end