import gov.ca.cwds.rest.exception.IssueDetails
import gov.ca.cwds.data.legacy.cms.entity.Client
import gov.ca.cwds.data.legacy.cms.entity.ClientScpEthnicity
import gov.ca.cwds.cms.data.access.dto.ClientEntityAwareDTO;

global java.util.Set validationDetailsList

rule "R-00742"
  dialect "mvel"
  agenda-group "client-agenda"
  when
      /*
        Code: R - 00742
        Rule Txt
        A client must have a 'primary ethnicity' in order to have an 'other ethnicity'
        Logic
        If CLIENT.Primary Ethnicity is blank, CLIENT_SCP_ETHNICITY.Ethnicity_Type must be blank.
      */
      $clientAwareDTO: ClientEntityAwareDTO()
      $client: Client() from $clientAwareDTO.entity
      $clientScpEthnicity : ClientScpEthnicity() from $clientAwareDTO.clientScpEthnicities
      Boolean(booleanValue == true) from $client.primaryEthnicityCode == (short)0 && $clientScpEthnicity.ethnctyc > (short)0


  then
      IssueDetails details = new IssueDetails();
      details.setCode("R-00742");
      details.setUserMessage("A client must have a 'primary ethnicity' in order to have an 'other ethnicity'.");
      details.setTechnicalMessage("If Client.primaryEthnicityCode is blank, ClientScpEthnicity.ethnctyc must be blank.");
      validationDetailsList.add(details);
end