import gov.ca.cwds.rest.exception.IssueDetails;
import gov.ca.cwds.data.legacy.cms.entity.Client;
import gov.ca.cwds.data.legacy.cms.entity.HealthInterventionPlan;
import gov.ca.cwds.cms.data.access.dto.ClientEntityAwareDTO;

global java.util.Set validationDetailsList

rule "R-00743"
  dialect "mvel"
  agenda-group "client-agenda"
  when
      /*
        Code: R-00743

        Rule Txt:
        A client must have a primary language in order to have a secondary language

        Logic:
        If CLIENT. Primary Language is blank, CLIENT. Secondary Language must be blank

      */
      clientAwareDTO: ClientEntityAwareDTO()
      client: Client(primaryLanguageCode == (short)0 && secondaryLanguageCode > (short)0 ) from clientAwareDTO.entity
  then
      IssueDetails details = new IssueDetails();
      details.setCode("R-00743");
      details.setUserMessage("A client must have a primary language in order to have a secondary language.");
      details.setTechnicalMessage("Client.primaryLanguageCode==null, Client.secondaryLanguageCode != null");
      validationDetailsList.add(details);
end