import gov.ca.cwds.rest.exception.IssueDetails
import gov.ca.cwds.data.legacy.cms.entity.Client
import gov.ca.cwds.cms.data.access.dto.ClientEntityAwareDTO;

global java.util.Set validationDetailsList

rule "R-00738"
  dialect "mvel"
  agenda-group "client-agenda"
  when
      /*
        Code: R - 00741
        Rule Txt
        The client's birth date must be less than or equal to the creation date of the Client record..
        Logic
        CLIENT.Creation_Date >= CLIENT.Birth_Date
      */
      $clientAwareDTO: ClientEntityAwareDTO()
      $client: Client(birthDate != null, creationDate != null, birthDate.isAfter(creationDate)) from $clientAwareDTO.entity
  then
      IssueDetails details = new IssueDetails();
      details.setCode("R-00738");
      details.setUserMessage("The client's birth date must be less than or equal to the creation date of the Client.");
      details.setTechnicalMessage("If Client.birthDate != null then should be: Client.creationDate >= Client.birthDate");
      validationDetailsList.add(details);
end
