import gov.ca.cwds.rest.exception.IssueDetails
import gov.ca.cwds.data.legacy.cms.entity.Client
import gov.ca.cwds.data.legacy.cms.entity.ClientOtherEthnicity
import gov.ca.cwds.cms.data.access.dto.ClientEntityAwareDTO;

global java.util.Set validationDetailsList

rule "R-00742"
  dialect "mvel"
  agenda-group "client-agenda"
  when
      /*
        Code: R - 00742
        Rule Txt
        A client must have a 'primary ethnicity' in order to have an 'other ethnicity'
        Logic
        If CLIENT.Primary Ethnicity is blank, CLIENT_SCP_ETHNICITY.Ethnicity_Type must be blank.
      */
      $clientAwareDTO: ClientEntityAwareDTO()
      $otherEthnicity : ClientOtherEthnicity($otherEthnicityCode : ethnicityCode) from $clientAwareDTO.otherEthnicities
      $client: Client(primaryEthnicityCode == (short)0, $otherEthnicityCode > (short)0) from $clientAwareDTO.entity


  then
      IssueDetails details = new IssueDetails();
      details.setCode("R-00742");
      details.setUserMessage("A client must have a 'primary ethnicity' in order to have an 'other ethnicity'.");
      details.setTechnicalMessage("If Client.primaryEthnicityCode is blank, ClientScpEthnicity.ethnctyc must be blank.");
      validationDetailsList.add(details);
end