import gov.ca.cwds.rest.exception.IssueDetails;
import gov.ca.cwds.data.legacy.cms.entity.ChildClient;
import gov.ca.cwds.data.legacy.cms.entity.CreditReportHistory;
import gov.ca.cwds.cms.data.access.dto.ChildClientEntityAwareDTO;

global java.util.Set validationDetailsList

rule "R-10787"
  dialect "mvel"
  agenda-group "client-agenda"
  when
      /*
        Code: R - 10787

        Rule Txt:
        The Request/Refusal Date cannot be less than the birth date of the Child Client.
        If the Request/Refusal Date is entered, then the Client's birth date cannot be changed
        to a date later than that of the Request/Refusal Date.

        Logic:
        CREDIT_REPORT_HISTORY.REQUEST_Date must be >= CLIENT.Birth_Date.
      */
      $clientAwareDTO: ChildClientEntityAwareDTO()
      $creditReport: CreditReportHistory($requestDate: requestRefusualDate) from $clientAwareDTO.getCreditReportHistories
      $client: ChildClient(birthDate != null, $requestDate == null || birthDate.isAfter($requestDate)) from $clientAwareDTO.entity
  then
      IssueDetails details = new IssueDetails();
      details.setCode("R-10787");
      details.setUserMessage("The Request/Refusal Date cannot be less than the birth date of the Child Client.\n"
                              + " If the Request/Refusal Date is entered, then the Client's birth date cannot be changed\n"
                              + " to a date later than that of the Request/Refusal Date.");
      details.setTechnicalMessage("If Client.birthDate != null then should be: CreditReportHistory.requestRefusualDate >= Client.birthDate");
      validationDetailsList.add(details);
end