import gov.ca.cwds.rest.exception.IssueDetails
import gov.ca.cwds.data.legacy.cms.entity.ChildClient
import gov.ca.cwds.cms.data.access.dto.ChildClientEntityAwareDTO;
import gov.ca.cwds.data.legacy.cms.entity.FCEligibility;

global java.util.Set<IssueDetails> validationDetailsList

rule "R-11126"
  dialect "mvel"
  agenda-group "client-agenda"
  when
      /*
        Code: R - 11126

        Rule text:
        The Eligibility (or Denial) Date must be greater than or equal to the Client's Birth Date (if it exists).

        Logic:
        AFDC_ELIGIBILITY.Date must be >= (If Exists) AFDC_ELIGIBILITY > CHILD_CLIENT > CLIENT.Birth_Date.

      */
      clientAwareDTO: ChildClientEntityAwareDTO()
      eligibility : FCEligibility(elDate : date) from clientAwareDTO.fcEligibilities
      client: ChildClient(birthDate != null && birthDate.isAfter(eligibility.date) && !birthDate.isEqual(eligibility.date)) from clientAwareDTO.entity

  then
      IssueDetails details = new IssueDetails();
      details.setCode("R-11126");
      details.setUserMessage("The client's birth date must be grater than or equal to the AfdcEligibility date.");
      details.setTechnicalMessage("If Client.birthDate != null then should be: CLIENT.birthDate >= AFDC_ELIGIBILITY.date");
      validationDetailsList.add(details);
end


