import gov.ca.cwds.rest.exception.IssueDetails
import gov.ca.cwds.data.legacy.cms.entity.Client
import gov.ca.cwds.cms.data.access.dto.ClientEntityAwareDTO;

global java.util.Set<IssueDetails> validationDetailsList

rule "R-00741"
  dialect "mvel"
  agenda-group "client-agenda"
  when
      /*
        Code: R - 11126

        Rule text:
        The Eligibility (or Denial) Date must be greater than or equal to the Client's Birth Date (if it exists).

        Logic:
        AFDC_ELIGIBILITY.Date must be >= (If Exists) AFDC_ELIGIBILITY > CHILD_CLIENT > CLIENT.Birth_Date.

      */
     $clientAwareDTO: ClientEntityAwareDTO()
     $client: Client(birthDate != null, deathDate != null, birthDate.isAfter(deathDate)) from $clientAwareDTO.entity
  then
      IssueDetails details = new IssueDetails();
      details.setCode("R-11126");
      details.setUserMessage("The client's birth date must be less than or equal to the death date of the client.");
      details.setTechnicalMessage("If Client.birthDate != null and Client.deathDate != null then should be: CLIENT.deathDate >= CLIENT.birthDate");
      validationDetailsList.add(details);
end


