import gov.ca.cwds.rest.exception.IssueDetails
import gov.ca.cwds.data.legacy.cms.entity.Client
import gov.ca.cwds.data.legacy.cms.entity.ClientRelationship
import gov.ca.cwds.cms.data.access.dto.ClientRelationshipAwareDTO;

global java.util.Set<IssueDetails> validationDetailsList

rule "R-00755"
  dialect "mvel"
  agenda-group "client-relationship-agenda"
  when
      /*
        Code: R - 00755

        Rule Txt:
          The START DATE cannot be later than END DATE.

        Logic:

      */
      $relationshipEntityAwareDto: ClientRelationshipAwareDTO()
      $clientRelationship : ClientRelationship(endDate != null && startDate != null && endDate.isBefore(startDate)) from $relationshipEntityAwareDto.entity
  then
      IssueDetails details = new IssueDetails();
      details.setCode("R-00755");
        details.setUserMessage(
            String.format(
              "The START DATE cannot be later than END DATE."
                  + " dateStart: '%s';"
                  + " dateEnd: %s'",
              $clientRelationship.getStartDate(),
              $clientRelationship.getEndDate()
            )
          );
      details.setTechnicalMessage("The START DATE cannot be later than END DATE.");
      validationDetailsList.add(details);
end
