import java.util.Collection;
import java.util.ArrayList;
import java.util.Arrays;

import gov.ca.cwds.rest.exception.IssueDetails
import gov.ca.cwds.data.legacy.cms.entity.Client
import gov.ca.cwds.data.legacy.cms.entity.ClientRelationship
import gov.ca.cwds.data.legacy.cms.entity.TribalMembershipVerification
import gov.ca.cwds.data.legacy.cms.entity.syscodes.ClientRelationshipType
import gov.ca.cwds.cms.data.access.dto.ClientRelationshipAwareDTO;

global java.util.Set validationDetailsList

rule "R-08861-0" salience 10
  dialect "mvel"
  agenda-group "client-relationship-data-processing-agenda"
  when

       $relationshipEntityAwareDto: ClientRelationshipAwareDTO()
       $clientRelationship : ClientRelationship() from $relationshipEntityAwareDto.entity
       $relationshipType: ClientRelationshipType(systemId == 189
                      || systemId == 190 || systemId == 251 || systemId == 192 || systemId == 252
                      || systemId == 195 || systemId == 284 || systemId == 196 || systemId == 285
                      || systemId == 198 || systemId == 287 || systemId == 204 || systemId == 290
                      || systemId == 205 || systemId == 291 || systemId == 207 || systemId == 5620
                      || systemId == 210 || systemId == 6360 || systemId == 211 || systemId == 6361
                      || systemId == 213 || systemId == 190 || systemId == 246 || systemId == 247)
                                              from $clientRelationship.type
  then
      $relationshipEntityAwareDto.setNeedMembershipVerification(true);
end

rule "R-08861-1" salience 1
  dialect "mvel"
  agenda-group "client-relationship-data-processing-agenda"
  when
      /*
      Code: R - 08861

      Rule Txt
       If (in focus) CLIENT_RELATIONSHIP > (parent) CLIENT > TRIBAL_MEMBERSHIP_VERIFICATION >
       TRIBAL_MEMBERSHIP_VERIFICATION (where in focus .Id = .FKTR_MBVRT and
       FK_CLIENT = (child) CLIENT.Id and .Indian_Enrollment_Status_Type <> null),
       and cboRelationship changed to something other than Permitted Parent Relationship,
       then give error and reset to previous value.
      */
    $relationshipEntityAwareDto: ClientRelationshipAwareDTO($isNeedMembershipVerification: needMembershipVerification)
    $tribalsForDelete: ArrayList() from accumulate(
        $tribalsThatHaveSubTribals: TribalMembershipVerification(
          indianEnrollmentStatus == null
          && $relationshipEntityAwareDto.needMembershipVerification == true
        ) from $relationshipEntityAwareDto.tribalsThatHaveSubTribals,
        collectList($tribalsThatHaveSubTribals)
    )
  then
  $relationshipEntityAwareDto.setTribalMembershipVerificationsForDelete($tribalsForDelete);
end
