import gov.ca.cwds.rest.exception.IssueDetails
import gov.ca.cwds.data.legacy.cms.entity.PlacementHome

global java.util.Set validationDetailsList

rule "R-03960"
  dialect "mvel"
  agenda-group "placement-home-agenda"
  when
      /*
      *Code:* R - 03960

      *Rule Txt*
      Placement home name is required for all county licensed (Non-LIS) foster family homes and resource family homes.

      *Logic*
      If PLACEMENT_HOME.Placement_Facility_Type = 'Foster Family Home' or 'Resource Family Home' and .Licenser_Code = 'CT', then txtName must <> null.
      */
      $placementHome: PlacementHome(facilityType == 1416 || facilityType == 6914, licensrCd == "CT", facltyNm == null)
  then
      IssueDetails details = new IssueDetails();
      details.setCode("R - 03960");
      details.setUserMessage("Placement home name is required for all county licensed (Non-LIS) foster family homes and resource family homes.");
      details.setTechnicalMessage("If PLACEMENT_HOME.Placement_Facility_Type = 'Foster Family Home' or 'Resource Family Home' and .Licenser_Code = 'CT', then txtName must <> null.");
      validationDetailsList.add(details);
end
