import gov.ca.cwds.rest.exception.IssueDetails
import gov.ca.cwds.data.legacy.cms.entity.PlacementHome
import gov.ca.cwds.cms.data.access.dto.PlacementHomeEntityAwareDTO;

global java.util.Set validationDetailsList

rule "R-03960"
  dialect "mvel"
  agenda-group "placement-home-agenda"
  when
      /*
      *Code:* R - 03960

      *Rule Txt*
      Placement home name is required for all county licensed (Non-LIS) foster family homes and resource family homes.

      *Logic*
      If PLACEMENT_HOME.Placement_Facility_Type = 'Foster Family Home' or 'Resource Family Home' and .Licenser_Code = 'CT', then txtName must <> null.
      */
      $placementHomeAwareDTO: PlacementHomeEntityAwareDTO()
      $placementHome: PlacementHome(facilityType == 1416 || facilityType == 6914, licensrCd == "CT", facltyNm == null) from $placementHomeAwareDTO.entity
  then
      IssueDetails details = new IssueDetails();
      details.setCode("R - 03960");
      details.setUserMessage("Placement home name is required for all county licensed (Non-LIS) foster family homes and resource family homes.");
      details.setTechnicalMessage("If PLACEMENT_HOME.Placement_Facility_Type = 'Foster Family Home' or 'Resource Family Home' and .Licenser_Code = 'CT', then txtName must <> null.");
      validationDetailsList.add(details);
end


rule "R-03855"
  dialect "mvel"
  agenda-group "placement-home-agenda"
  when
      /*;
        Code: R - 03855
        Rule Txt
        The maximum age must be less than 26 years old.
        Logic
        For a GHO, the GROUP_HOME_ORGANIZATION.ACCEPTED_AGE_RANGE_TO_NUMBER must be < 26. For a Placement Home or FFA, the PLACEMENT_HOME.ACCEPTED_AGE_RANGE_TO_NUMBER must be < 26.
      */
      $placementHomeAwareDTO: PlacementHomeEntityAwareDTO()
      $placementHome: PlacementHome(ageToNo > 25) from $placementHomeAwareDTO.entity
  then
      IssueDetails details = new IssueDetails();
      details.setCode("R - 03855");
      details.setUserMessage("The maximum age must be less than 26 years old.");
      details.setTechnicalMessage("For a GHO, the GROUP_HOME_ORGANIZATION.ACCEPTED_AGE_RANGE_TO_NUMBER must be < 26. For a Placement Home or FFA, the PLACEMENT_HOME.ACCEPTED_AGE_RANGE_TO_NUMBER must be < 26.");
      validationDetailsList.add(details);
end
