import gov.ca.cwds.rest.exception.IssueDetails
import gov.ca.cwds.data.legacy.cms.entity.PlacementHome
import gov.ca.cwds.data.legacy.cms.entity.EmergencyContactDetail
import gov.ca.cwds.cms.data.access.dto.PlacementHomeEntityAwareDTO;
import org.apache.commons.lang3.StringUtils

global java.util.Set validationDetailsList


/*
        Code: R - 09753

        Rule Txt
        If Street Number is entered, then Street Name is mandatory.
*/

rule "R-09753"
  dialect "mvel"
  agenda-group "placement-home-agenda"
  when
      $placementHomeAwareDTO: PlacementHomeEntityAwareDTO()
      EmergencyContactDetail(eval(StringUtils.isNotBlank(streetNo) && StringUtils.isBlank(streetNm))) from  $placementHomeAwareDTO.emergencyContactDetail
  then
      IssueDetails details = new IssueDetails();
      details.setCode("R-09753");
      details.setUserMessage("Street name must not be empty if Street no is entered");
      details.setTechnicalMessage("If Street Number is entered, then Street Name is mandatory.");
      validationDetailsList.add(details);
end
