import gov.ca.cwds.rest.exception.IssueDetails
import gov.ca.cwds.data.legacy.cms.entity.PlacementHome
import gov.ca.cwds.cms.data.access.dto.PlacementHomeEntityAwareDTO;
import gov.ca.cwds.security.realm.PerryAccount
import gov.ca.cwds.data.legacy.cms.entity.PlacementFacilityTypeHistory
import java.time.LocalDateTime
import java.util.Arrays;

global java.util.Set validationDetailsList

rule "R-11179"
  dialect "mvel"
  agenda-group "placement-home-data-processing-agenda"
  when
      /*
        Rule Txt

        If the placement home is being saved to the database for the first time then create a
        new Placement Facility Type History row.

        Logic

        If (in focus) PLACEMENT_HOME is saved to the database for the first time then create
        PLACEMENT_HOME > PLACEMENT_FACILITY_TYPE_HISTORY
        set .Start_Timestamp = System Timestamp
        AND .Placement_Facility_Type = (in focus) PLACEMENT_HOME.Placement_Facility_Type.
      */
      $placementHomeAwareDTO: PlacementHomeEntityAwareDTO()
      $placementHome: PlacementHome(placementFacilityTypeHistory == null) from $placementHomeAwareDTO.entity
  then
      PlacementFacilityTypeHistory placementFacilityTypeHistory = new PlacementFacilityTypeHistory();
      placementFacilityTypeHistory.setStartTimestamp(LocalDateTime.now());
      placementFacilityTypeHistory.setCreationTimestamp(LocalDateTime.now());
      placementFacilityTypeHistory.setPlacementFacilityType($placementHome.getFacilityType());
      $placementHome.setPlacementFacilityTypeHistory(Arrays.asList(placementFacilityTypeHistory));
      update ($placementHomeAwareDTO);
end
