import gov.ca.cwds.rest.exception.IssueDetails
import gov.ca.cwds.data.legacy.cms.entity.PlacementHome
import gov.ca.cwds.cms.data.access.dto.PlacementHomeEntityAwareDTO;
import gov.ca.cwds.security.realm.PerryAccount;

global java.util.Set validationDetailsList

rule "R-11037"
  dialect "mvel"
  agenda-group "placement-home-agenda"
  when
      /*
      *Code:* R - 11037

      *Rule Txt*
      In the Resource Management Application,
       a staff person with the privilege of "Resource Mgmt Placement Facility Maint" can add
       a Resource Family Home

      *Logic*
      Allow Resource Family Home add if (STAFF_PERSON (logged on user) > USER_ID > STAFF_PERSON_PRIVILEGE.Level_Of_Auth_Privilege_Code = 'P' and STAFF_PERSON_PRIVILEGE.Level_Of_Auth_Privilege_Type = 'Resource Mgmt Placement Facility Maint')
      */
      $placementHomeAwareDTO: PlacementHomeEntityAwareDTO()
      PerryAccount(privileges not contains "Resource Mgmt Placement Facility Maint")
  then
      IssueDetails details = new IssueDetails();
      details.setCode("R-11037");
      details.setUserMessage("Staff person must have \"Resource Mgmt Placement Facility Maint\" privilege to be able to create Resource Family Home");
      details.setTechnicalMessage("Viloation of rule: Allow Resource Family Home add if (STAFF_PERSON (logged on user) > USER_ID > STAFF_PERSON_PRIVILEGE.Level_Of_Auth_Privilege_Code = 'P' and STAFF_PERSON_PRIVILEGE.Level_Of_Auth_Privilege_Type = 'Resource Mgmt Placement Facility Maint')");
      validationDetailsList.add(details);
end


