package gov.ca.cwds.data.legacy.cms.entity;

import gov.ca.cwds.data.persistence.PersistentObject;
import java.io.Serializable;
import java.time.LocalDateTime;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

/**
 * @author CWDS CALS API Team
 *
 * Associates a specific ethnicity (e.g., Black, Chinese, Hawaiian) with a specific CLIENT or SCP.
 */
@Entity
@Table(name = "CLSCP_ET")
@SuppressWarnings({"squid:S3437"}) //LocalDate is serializable
public class ClientScpEthnicity implements PersistentObject {

  private static final long serialVersionUID = -3907876485597227714L;

  /**
   * ID - A system generated number used to uniquely identify each CLIENT_SCP_ETHNICITY. This ID is
   * composed of a base 62 Creation Timestamp and the STAFF_PERSON ID (a sequential 3 digit base 62
   * number generated by the system). This value eliminates the need for an additional set of
   * Creation Timestamp and Creation User ID which is needed to satisfy the Audit Trail requirement.
   */
  @Id
  @Column(name = "IDENTIFIER", nullable = false, length = 10)
  private String identifier;

  /**
   * ETHNICITY_TYPE - The system generated number which identifies the type of ethnicity for the
   * SUBSTITUTE CARE PROVIDER.
   */
  @Basic
  @Column(name = "ETHNCTYC", nullable = false)
  private Short ethnctyc;

  /**
   * ESTABLISHED_FOR_ID - The logical foreign key representing the ID from the recipient entity for
   * which a CLIENT_SCP_ETHNICITY was identified (e.g., the ID from the CLIENT or
   * SUBSTITUTE_CARE_PROVIDER entity types).
   */
  @Basic
  @Column(name = "ESTBLSH_ID", nullable = false, length = 10)
  private String estblshId;

  /**
   * ESTABLISHED_FOR_CODE - This code defines each type of recipient entity for which a specific
   * CLIENT_SCP_ETHNICITY was identified (e.g. C = CLIENT, S = SUBSTITUTE_CARE_PROVIDER).
   */
  @Basic
  @Column(name = "ESTBLSH_CD", nullable = false, length = 1)
  private String estblshCd;

  /**
   * LAST_UPDATE_ID - The ID (a sequential 3 digit base 62 number generated by the system) of the
   * STAFF PERSON or batch program which made the last update to an occurrence of this entity type.
   */
  @Basic
  @Column(name = "LST_UPD_ID", nullable = false, length = 3)
  private String lstUpdId;

  /**
   * LAST_UPDATE_TIMESTAMP - The time and date of the most recent update to an occurrence of this
   * entity type.
   */
  @Basic
  @Column(name = "LST_UPD_TS", nullable = false)
  private LocalDateTime lstUpdTs;

  public String getIdentifier() {
    return identifier;
  }

  public void setIdentifier(String identifier) {
    this.identifier = identifier;
  }

  public Short getEthnctyc() {
    return ethnctyc;
  }

  public void setEthnctyc(Short ethnctyc) {
    this.ethnctyc = ethnctyc;
  }

  public String getEstblshId() {
    return estblshId;
  }

  public void setEstblshId(String estblshId) {
    this.estblshId = estblshId;
  }

  public String getEstblshCd() {
    return estblshCd;
  }

  public void setEstblshCd(String estblshCd) {
    this.estblshCd = estblshCd;
  }

  public String getLstUpdId() {
    return lstUpdId;
  }

  public void setLstUpdId(String lstUpdId) {
    this.lstUpdId = lstUpdId;
  }

  public LocalDateTime getLstUpdTs() {
    return lstUpdTs;
  }

  public void setLstUpdTs(LocalDateTime lstUpdTs) {
    this.lstUpdTs = lstUpdTs;
  }

  @Override
  public boolean equals(Object o) {
    return EqualsBuilder.reflectionEquals(this, o);
  }

  @Override
  public int hashCode() {
    return HashCodeBuilder.reflectionHashCode(this);
  }

  @Override
  public Serializable getPrimaryKey() {
    return getIdentifier();
  }
}
