package gov.ca.cwds.data.legacy.cms.entity;

import java.io.Serializable;
import java.time.LocalDateTime;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

import gov.ca.cwds.data.persistence.PersistentObject;

/**
 * @author CWDS CALS API Team
 *
 *         This entity type describes the relationship between a SUBSTITUTE CARE PROVIDER and other
 *         people in the PLACEMENT HOME. These other people can be OTHER CHILDREN IN PLACEMENT or
 *         OTHER ADULTS IN PLACEMENT HOME.
 */
@Entity
@Table(name = "OPSCPRLT")
@SuppressWarnings({"squid:S3437"}) // LocalDate is serializable
public class OtherPeopleScpRelationship implements PersistentObject {

  private static final long serialVersionUID = 1707693062140240447L;

  /**
   * ID - A system generated number used to uniquely identify each OTHER_PEOPLE_SCP_RELATIONSHIP.
   * This ID is composed of a base 62 Creation Timestamp and the STAFF_PERSON ID (a sequential 3
   * digit base 62 number generated by the system). This value eliminates the need for an additional
   * set of Creation Timestamp and Creation User ID which is needed to satisfy the Audit Trail
   * requirement.
   */
  @Id
  @Column(name = "IDENTIFIER", nullable = false, length = 10)
  private String identifier;

  /**
   * RELATIONSHIP_TYPE - The system generated number designated for each type of relationship
   * between a SUBSTITUTE_CARE_PROVIDER and either an OTHER_CHILDREN_IN_PLACEMENT_HOME or
   * OTHER_ADULTS_IN_PLACEMENT_HOME (e.g. son/father, daughter/father, sister/brother, etc.).
   */
  @Basic
  @Column(name = "CLNTRELC", nullable = false)
  private short clntrelc;

  /**
   * LAST_UPDATE_ID - The ID (a sequential 3 digit base 62 number generated by the system) of the
   * STAFF PERSON or batch program which made the last update to an occurrence of this entity type.
   */
  @Basic
  @Column(name = "LST_UPD_ID", nullable = false, length = 3)
  private String lstUpdId;

  /**
   * LAST_UPDATE_TIMESTAMP - The time and date of the most recent update to an occurrence of this
   * entity type.
   */
  @Basic
  @Column(name = "LST_UPD_TS", nullable = false)
  private LocalDateTime lstUpdTs;

  /**
   * FKOTH_ADLT - Optional Foreign key that RELATES_SCP_TO_ADULT_IN a
   * OTHER_ADULTS_IN_PLACEMENT_HOME.
   */
  @Basic
  @Column(name = "FKOTH_ADLT", nullable = true, length = 10)
  private String fkothAdlt;

  /**
   * FKOTH_KIDT - Optional Foreign key that RELATES_SCP_TO_CHILD_IN a
   * OTHER_CHILDREN_IN_PLACEMENT_HOME.
   */
  @Basic
  @Column(name = "FKOTH_KIDT", nullable = true, length = 10)
  private String fkothKidt;

  /**
   * FKSB_PVDRT - Mandatory Foreign key that RELATES_ADULT_OR_CHILD_TO_SCP_IN a
   * SUBSTITUTE_CARE_PROVIDER. <blockquote>
   * 
   * <pre>
   * &#64;Basic
   * &#64;Column(name = "FKSB_PVDRT", nullable = false, length = 10)
   * private String fksbPvdrt;
   * </pre>
   * 
   * </blockquote>
   */
  @NotFound(action = NotFoundAction.IGNORE)
  @ManyToOne
  @Fetch(FetchMode.SELECT)
  @JoinColumn(name = "FKSB_PVDRT", referencedColumnName = "IDENTIFIER")
  private SubstituteCareProvider substituteCareProvider;


  public String getIdentifier() {
    return identifier;
  }

  public void setIdentifier(String identifier) {
    this.identifier = identifier;
  }

  public short getClntrelc() {
    return clntrelc;
  }

  public void setClntrelc(short clntrelc) {
    this.clntrelc = clntrelc;
  }

  public String getLstUpdId() {
    return lstUpdId;
  }

  public void setLstUpdId(String lstUpdId) {
    this.lstUpdId = lstUpdId;
  }

  public LocalDateTime getLstUpdTs() {
    return lstUpdTs;
  }

  public void setLstUpdTs(LocalDateTime lstUpdTs) {
    this.lstUpdTs = lstUpdTs;
  }

  public String getFkothAdlt() {
    return fkothAdlt;
  }

  public void setFkothAdlt(String fkothAdlt) {
    this.fkothAdlt = fkothAdlt;
  }

  public String getFkothKidt() {
    return fkothKidt;
  }

  public void setFkothKidt(String fkothKidt) {
    this.fkothKidt = fkothKidt;
  }

  public SubstituteCareProvider getSubstituteCareProvider() {
    return substituteCareProvider;
  }

  public void setSubstituteCareProvider(SubstituteCareProvider substituteCareProvider) {
    this.substituteCareProvider = substituteCareProvider;
  }

  @Override
  public boolean equals(Object o) {
    return EqualsBuilder.reflectionEquals(this, o);
  }

  @Override
  public int hashCode() {
    return HashCodeBuilder.reflectionHashCode(this);
  }

  @Override
  public Serializable getPrimaryKey() {
    return getIdentifier();
  }
}
