package gov.ca.cwds.data.legacy.cms.entity;

import gov.ca.cwds.data.persistence.PersistentObject;
import java.io.Serializable;
import java.time.LocalDate;
import java.time.LocalDateTime;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;
import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

/**
 * @author CWDS CALS API Team
 *
 * An adult who is either the home licensee and/or a home resident care provider.
 *
 */
@Entity
@Table(name = "HM_SCP_T")
@IdClass(PlacementHomeInformationPK.class)
@SuppressWarnings({"squid:S3437"}) //LocalDate is serializable
public class PlacementHomeInformation implements PersistentObject {

  private static final long serialVersionUID = 6456312577863311399L;
  
  /**
   * THIRD_ID - This is a system generated unique number that supplements user supplied data in the
   * primary key. The Third ID attribute will be used as part of the new Primary Key in combination
   * with user supplied data. It will also be used alone as a separate key for direct access. This
   * Third ID is composed of a base 62 Creation Timestamp and the STAFF_PERSON ID (a sequential 3
   * digit base 62 number generated by the system).
   */
  @Id
  @Column(name = "THIRD_ID", nullable = false, length = 10)
  private String thirdId;

  /**
   * START_DATE - The date the SUBSTITUTE CARE PROVIDER first becomes associated with the PLACEMENT
   * HOME.
   */
  @Basic
  @Column(name = "START_DT", nullable = false)
  private LocalDate startDt;

  /**
   * END_DATE - The date the SUBSTITUTE CARE PROVIDER terminates his/her association with the
   * PLACEMENT HOME.
   */
  @Basic
  @Column(name = "END_DT", nullable = true)
  private LocalDate endDt;

  /**
   * LICENSEE_CODE - Indicates whether this person holds the LICENSE for this PLACEMENT HOME (who
   * may or may not be different from the person providing daily care and supervision at the
   * PLACEMENT HOME).
   */
  @Basic
  @Column(name = "LICNSEE_CD", nullable = false, length = 1)
  private String licnseeCd;

  /** CARE_PROVIDER_CODE - Indicates whether this person resides at the Placement Home. */
  @Basic
  @Column(name = "CRPRVDR_CD", nullable = false, length = 1)
  private String crprvdrCd;

  /**
   * LAST_UPDATE_ID - The ID (a sequential 3 digit base 62 number generated by the system) of the
   * STAFF PERSON or batch program which made the last update to an occurrence of this entity type.
   */
  @Basic
  @Column(name = "LST_UPD_ID", nullable = false, length = 3)
  private String lstUpdId;

  /**
   * LAST_UPDATE_TIMESTAMP - The date and time of the most recent update to an occurrence of this
   * entity type.
   */
  @Basic
  @Column(name = "LST_UPD_TS", nullable = false)
  private LocalDateTime lstUpdTs;

  /** FKSB_PVDRT - Mandatory Foreign key that DESIGNATES a SUBSTITUTE_CARE_PROVIDER. */
  @Id
  @Column(name = "FKSB_PVDRT", nullable = false, length = 10)
  private String fksbPvdrt;

  /** FKPLC_HM_T - Mandatory Foreign key that PROVIDES_SUBSTITUTE_CARE_FOR a PLACEMENT_HOME. */
  @Id
  @Column(name = "FKPLC_HM_T", nullable = false, length = 10)
  private String fkplcHmT;

  /**
   * PRIMARY_PROVIDER_IND - Indicates whether this person is the primary provider of daily care and
   * supervision at the PLACEMENT HOME. Valid values are Y (Primary Provider) and N (Not Primary
   * Provider)
   */
  @Basic
  @Column(name = "PRPRVDR_CD", nullable = false, length = 1)
  private String prprvdrCd;

  /**
   * CDS_PERSON_NUMBER - A two digit number assigned to a specific individual within the Case Data
   * System (CDS) case, etc. This is the fifth component which forms the fourteen digit state
   * identification number.
   */
  @Basic
  @Column(name = "CDS_PRSN", nullable = false, length = 2)
  private String cdsPrsn;

  /**
   * SECONDARY_PROVIDER_IND - Indicates whether this person is the secondary provider of daily care
   * and supervision at the PLACEMENT_HOME. Valid values are Y (Secondary Provider) and N (Not
   * Secondary Provider).
   */
  @Basic
  @Column(name = "SCPRVD_IND", nullable = false, length = 1)
  private String scprvdInd;

  public String getThirdId() {
    return thirdId;
  }

  public void setThirdId(String thirdId) {
    this.thirdId = thirdId;
  }

  public LocalDate getStartDt() {
    return startDt;
  }

  public void setStartDt(LocalDate startDt) {
    this.startDt = startDt;
  }

  public LocalDate getEndDt() {
    return endDt;
  }

  public void setEndDt(LocalDate endDt) {
    this.endDt = endDt;
  }

  public String getLicnseeCd() {
    return licnseeCd;
  }

  public void setLicnseeCd(String licnseeCd) {
    this.licnseeCd = licnseeCd;
  }

  public String getCrprvdrCd() {
    return crprvdrCd;
  }

  public void setCrprvdrCd(String crprvdrCd) {
    this.crprvdrCd = crprvdrCd;
  }

  public String getLstUpdId() {
    return lstUpdId;
  }

  public void setLstUpdId(String lstUpdId) {
    this.lstUpdId = lstUpdId;
  }

  public LocalDateTime getLstUpdTs() {
    return lstUpdTs;
  }

  public void setLstUpdTs(LocalDateTime lstUpdTs) {
    this.lstUpdTs = lstUpdTs;
  }

  public String getFksbPvdrt() {
    return fksbPvdrt;
  }

  public void setFksbPvdrt(String fksbPvdrt) {
    this.fksbPvdrt = fksbPvdrt;
  }

  public String getFkplcHmT() {
    return fkplcHmT;
  }

  public void setFkplcHmT(String fkplcHmT) {
    this.fkplcHmT = fkplcHmT;
  }

  public String getPrprvdrCd() {
    return prprvdrCd;
  }

  public void setPrprvdrCd(String prprvdrCd) {
    this.prprvdrCd = prprvdrCd;
  }

  public String getCdsPrsn() {
    return cdsPrsn;
  }

  public void setCdsPrsn(String cdsPrsn) {
    this.cdsPrsn = cdsPrsn;
  }

  public String getScprvdInd() {
    return scprvdInd;
  }

  public void setScprvdInd(String scprvdInd) {
    this.scprvdInd = scprvdInd;
  }

  @Override
  public boolean equals(Object o) {
    return EqualsBuilder.reflectionEquals(this, o);
  }

  @Override
  public int hashCode() {
    return HashCodeBuilder.reflectionHashCode(this);
  }

  @Override
  public Serializable getPrimaryKey() {
    return new PlacementHomeInformationPK(thirdId, fksbPvdrt, fkplcHmT);
  }
}
