package gov.ca.cwds.data.legacy.cms.entity;

import gov.ca.cwds.data.persistence.PersistentObject;
import java.io.Serializable;
import java.time.LocalDateTime;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

/**
 * @author CWDS CALS API Team
 *
 * The converted (uppercase) name of the SUBSTITUTE_CARE PROVIDER to be used for Substitute Care
 * Provider Search.
 */
@Entity
@Table(name = "SBPVD_UC")
@SuppressWarnings({"squid:S3437"}) //LocalDate is serializable
public class SubstituteCareProviderUc implements PersistentObject {


  private static final long serialVersionUID = -1444722667168021623L;

  /**
   * PKSB_PVDRT - Mandatory Foreign key that DEFINES_THE_SEARCH_KEY_FOR a SUBSTITUTE_CARE_PROVIDER.
   */
  @Id
  @Column(name = "PKSB_PVDRT", nullable = false, length = 10)
  private String pksbPvdrt;

  /**
   * CA_DRIVER_LICENSE_NUMBER - The driver license number of the SUBSTITUTE CARE  PROVIDER.
   */
  @Basic
  @Column(name = "CA_DLIC_NO", nullable = false, length = 8)
  private String caDlicNo;

  /**
   * FIRST_NAME - The first name of the SUBSTITUTE CARE PROVIDER.
   */
  @Basic
  @Column(name = "FIRST_NM", nullable = false, length = 20)
  private String firstNm;

  /**
   * LAST_NAME - The last name of the SUBSTITUTE CARE PROVIDER.
   */
  @Basic
  @Column(name = "LAST_NM", nullable = false, length = 25)
  private String lastNm;

  /**
   * LAST_UPDATE_ID - The ID (a sequential 3 digit base 62 number generated by the system) of the
   * STAFF PERSON or batch program which made the last update to an occurrence of this entity type.
   */
  @Basic
  @Column(name = "LST_UPD_ID", nullable = false, length = 3)
  private String lstUpdId;

  /**
   * LAST_UPDATE_TIMESTAMP - The date and time of the most recent update to an occurrence of this
   * entity type.
   */
  @Basic
  @Column(name = "LST_UPD_TS", nullable = false)
  private LocalDateTime lstUpdTs;

  public String getPksbPvdrt() {
    return pksbPvdrt;
  }

  public void setPksbPvdrt(String pksbPvdrt) {
    this.pksbPvdrt = pksbPvdrt;
  }

  public String getCaDlicNo() {
    return caDlicNo;
  }

  public void setCaDlicNo(String caDlicNo) {
    this.caDlicNo = caDlicNo;
  }

  public String getFirstNm() {
    return firstNm;
  }

  public void setFirstNm(String firstNm) {
    this.firstNm = firstNm;
  }

  public String getLastNm() {
    return lastNm;
  }

  public void setLastNm(String lastNm) {
    this.lastNm = lastNm;
  }

  public String getLstUpdId() {
    return lstUpdId;
  }

  public void setLstUpdId(String lstUpdId) {
    this.lstUpdId = lstUpdId;
  }

  public LocalDateTime getLstUpdTs() {
    return lstUpdTs;
  }

  public void setLstUpdTs(LocalDateTime lstUpdTs) {
    this.lstUpdTs = lstUpdTs;
  }

  @Override
  public boolean equals(Object o) {
    return EqualsBuilder.reflectionEquals(this, o);
  }

  @Override
  public int hashCode() {
    return HashCodeBuilder.reflectionHashCode(this);
  }

  @Override
  public Serializable getPrimaryKey() {
    return getPksbPvdrt();
  }
}
