package gov.ca.cwds.data.persistence.cms;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import gov.ca.cwds.rest.api.ApiException;
import gov.ca.cwds.data.persistence.cms.CmsSystemCodeCache.*;
import static org.hamcrest.CoreMatchers.*;
import static org.junit.Assert.*;
import static org.mockito.BDDMockito.*;

import static org.hamcrest.CoreMatchers.notNullValue;
import static org.junit.Assert.assertThat;
import static org.junit.Assert.assertTrue;

import java.io.IOException;
import java.util.List;

import org.junit.Test;

import gov.ca.cwds.data.persistence.cms.CmsSystemCodeCache.CmsSystemCode;

public class CmsSystemCodeCacheTest {

  @Test
  public void type() throws Exception {
    assertThat(CmsSystemCodeCache.class, notNullValue());
  }

  @Test
  public void instantiation() throws Exception {
    CmsSystemCodeCache target = makeCache();
    assertThat(target, notNullValue());
  }

  @Test
  public void lookup_Args$int() throws Exception {
    CmsSystemCodeCache target = makeCache();
    // given
    int sysId = 297;
    // e.g. : given(mocked.called()).willReturn(1);
    // when
    final CmsSystemCode actual = target.lookup(sysId);
    // then
    // e.g. : verify(mocked).called();
    assertTrue("CLNTRELC".equals(actual.getFksMetaT()));
  }

  @Test
  public void getCategory_Args$String() throws Exception {
    CmsSystemCodeCache target = makeCache();
    // given
    final String meta = "CLT_CONC";
    // e.g. : given(mocked.called()).willReturn(1);
    // when
    List<CmsSystemCode> actual = target.getCategory(meta);
    // then
    // e.g. : verify(mocked).called();
    assertTrue(actual.size() > 0);
  }

  // @Test
  // public void produce_Args$File() throws Exception {
  // // given
  // File file = mock(File.class);
  // // e.g. : given(mocked.called()).willReturn(1);
  // // when
  // CmsSystemCodeCache actual = CmsSystemCodeCache.produce(file);
  // // then
  // // e.g. : verify(mocked).called();
  // CmsSystemCodeCache expected = null;
  // assertThat(actual, is(equalTo(expected)));
  // }

  @Test
  public void produce_Args$() throws Exception {
    // given
    // e.g. : given(mocked.called()).willReturn(1);
    // when
    CmsSystemCodeCache actual = CmsSystemCodeCache.produce();
    final CmsSystemCode code = actual.lookup(280);
    // then
    // e.g. : verify(mocked).called();
    assertTrue(code != null);
  }

  private static CmsSystemCodeCache makeCache() throws IOException {
    return CmsSystemCodeCache.produce();
  }

	@Test
	public void produce_Args$BufferedReader() throws Exception {
		// TODO auto-generated by JUnit Helper.
		// given
		BufferedReader reader = mock(BufferedReader.class);
		// e.g. : given(mocked.called()).willReturn(1);
		// when
		CmsSystemCodeCache actual = CmsSystemCodeCache.produce(reader);
		// then
		// e.g. : verify(mocked).called();
		CmsSystemCodeCache expected = null;
		assertThat(actual, is(equalTo(expected)));
	}

	@Test
	public void produce_Args$BufferedReader_T$IOException() throws Exception {
		// TODO auto-generated by JUnit Helper.
		// given
		BufferedReader reader = mock(BufferedReader.class);
		// e.g. : given(mocked.called()).willReturn(1);
		try {
			// when
			CmsSystemCodeCache.produce(reader);
			fail("Expected exception was not thrown!");
		} catch (IOException e) {
			// then
		}
	}

	@Test
	public void produce_Args$File() throws Exception {
		// TODO auto-generated by JUnit Helper.
		// given
		File file = mock(File.class);
		// e.g. : given(mocked.called()).willReturn(1);
		// when
		CmsSystemCodeCache actual = CmsSystemCodeCache.produce(file);
		// then
		// e.g. : verify(mocked).called();
		CmsSystemCodeCache expected = null;
		assertThat(actual, is(equalTo(expected)));
	}

}
